"""
Django settings for motor_ia project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import sys
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Permite importar la app api_destinos ubicada dentro del caso de uso CU-06.
CU06_APP_DIR = BASE_DIR / "deeplearning" / "CU06_buscar_destinos"
if str(CU06_APP_DIR) not in sys.path:
    sys.path.insert(0, str(CU06_APP_DIR))

# Permite importar la app api_reels ubicada dentro del caso de uso CU-07.
CU07_APP_DIR = BASE_DIR / "deeplearning" / "CU07_generar_reels"
if str(CU07_APP_DIR) not in sys.path:
    sys.path.insert(0, str(CU07_APP_DIR))

# Permite importar la app api_traductor ubicada dentro del caso de uso CU-08.
CU08_APP_DIR = BASE_DIR / "deeplearning" / "CU08_traductor_visual"
if str(CU08_APP_DIR) not in sys.path:
    sys.path.insert(0, str(CU08_APP_DIR))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-he23-q(9n$8#x7d4gv@iu3(s@!fplb0^fi4+&r_4+n#^o1p()p'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'api_destinos.apps.ApiDestinosConfig',
    'api_reels.apps.ApiReelsConfig',
    'api_traductor.apps.ApiTraductorConfig',
    'machinelearning.CU09_Recomendacion_personalizada.apps.Cu09RecomendacionPersonalizadaConfig',
    'machinelearning.CU10_Deteccion_de_patrones.apps.Cu10DeteccionPatronesViajeConfig',
    'machinelearning.CU11_Segementacion_clientes.apps.ApiSegmentacionConfig',
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'motor_ia.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'motor_ia.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Media files (archivos generados por la IA: reels, etc.)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Límite de tamaño para uploads de archivos (150 MB para videos)
DATA_UPLOAD_MAX_MEMORY_SIZE = 157286400      # 150 MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 157286400      # 150 MB

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
