spring.application.name=core-transaccional

# PostgreSQL connection
spring.datasource.url=jdbc:postgresql://localhost:5432/core_transaccional_db
spring.datasource.username=postgres
spring.datasource.password=nicolas123   

# JPA properties
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Optional: for lazy loading
spring.jpa.properties.hibernate.enable_lazy_load_no_trans=true